# Generated by Django 4.2.9 on 2024-01-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(1, '☆ '), (2, '☆ ☆ '), (3, '☆ ☆ ☆ '), (4, '☆ ☆ ☆ ☆ '), (5, '☆ ☆ ☆ ☆ ☆ ')], default=5),
        ),
    ]
